# Example: Copy this to your repo as .github/workflows/dependency-review.yml
name: Dependency Review

on: [pull_request]

jobs:
  dependency-review:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-dependency-review.yml@288f393bf5407c87ffd95c128cdf694761941308 # v0.2.0
    secrets: inherit
