# Example: Copy this to your repo as .github/workflows/dependency-review.yml
name: Dependency Review

on: [pull_request]

jobs:
  dependency-review:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-dependency-review.yml@ab9c1504e30dcc5928d86d9e0147bc1ceb35383c # v0.1.0
    secrets: inherit
