# Example: Copy this to your repo as .github/workflows/dependency-review.yml
name: Dependency Review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dependency-review:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-dependency-review.yml@ffe58c94e5025487cd4c6cab741289d722675378 # v0.2.2
    permissions:
      contents: read
      pull-requests: write
