# Example: Copy this to your repo as .github/workflows/dependency-review.yml
name: Dependency Review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dependency-review:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-dependency-review.yml@3809a757f2f69d0d12443ea9554af0136ba66320 # v0.2.1
    permissions:
      contents: read
      pull-requests: write
