# Example: Copy this to your repo as .github/workflows/maven.yml
# Configuration is read from .github/project.yml - no inputs needed!
# Path filtering is handled inside the reusable workflow via project.yml settings.
name: Maven Build

on:
  push:
    branches: [main, "feature/*", "fix/*", "chore/*", "release/*", "dependabot/**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # Run on push events, OR on pull_request only if from a fork
    # This prevents duplicate runs: push handles internal branches, PR handles forks
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: cuioss/cuioss-organization/.github/workflows/reusable-maven-build.yml@fbb87b2940f43cd3c6907c194dbbd437b2a78aa4 # v0.5.0
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      OSS_SONATYPE_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
      OSS_SONATYPE_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
