# Example: Maven build with custom options (override project.yml settings)
name: Maven Build

on:
  push:
    branches: [main, "feature/*", "fix/*", "chore/*", "dependabot/**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    # Run on push events, OR on pull_request only if from a fork
    # This prevents duplicate runs: push handles internal branches, PR handles forks
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: cuioss/cuioss-organization/.github/workflows/reusable-maven-build.yml@89ce95e04b1e15076b0c8d78d8112fa432d9d162 # v0.3.11
    with:
      # Override project.yml settings with explicit inputs
      java-versions: '["21","25"]'
      enable-sonar: true
      enable-snapshot-deploy: true
      npm-cache: true  # Enable for projects with frontend
      maven-profiles-snapshot: 'release-snapshot,javadoc'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      OSS_SONATYPE_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
      OSS_SONATYPE_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
