# Example: Copy this to your repo as .github/workflows/maven.yml
# Configuration is read from .github/project.yml - no inputs needed!
name: Maven Build

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-maven-build.yml@ab9c1504e30dcc5928d86d9e0147bc1ceb35383c # v0.1.0
    secrets: inherit
