# Example: Copy this to your repo as .github/workflows/release.yml
# Configuration is read from .github/project.yml - no inputs needed!
name: Release

on:
  pull_request:
    types: [closed]
    paths:
      - '.github/project.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: cuioss/cuioss-organization/.github/workflows/reusable-maven-release.yml@ab9c1504e30dcc5928d86d9e0147bc1ceb35383c # v0.1.0
    secrets: inherit
