# Example: Copy this to your repo as .github/workflows/maven.yml
# Configuration is read from .github/project.yml - no inputs needed!
name: Maven Build

on:
  push:
    branches: [main, "feature/*", "fix/*", "chore/*", "release/*", "dependabot/**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-changes:
    runs-on: ubuntu-latest
    # Run on push events, OR on pull_request only if from a fork
    # This prevents duplicate runs: push handles internal branches, PR handles forks
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    outputs:
      should-run: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            code:
              - '!**/*.adoc'
              - '!**/*.md'
              - '!doc/**'
              - '!.github/project.yml'
              - '!.github/dependabot.yml'
              - '!LICENSE'
              - '!NOTICE'

  build:
    needs: check-changes
    if: needs.check-changes.outputs.should-run == 'true'
    uses: cuioss/cuioss-organization/.github/workflows/reusable-maven-build.yml@421483d5b133e02e6d6f1a0f2e800bedb7869122 # v0.2.9
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      OSS_SONATYPE_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
      OSS_SONATYPE_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
