# Example: Copy this to your repo as .github/workflows/maven.yml
# Configuration is read from .github/project.yml - no inputs needed!
name: Maven Build

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Prevent duplicate runs when pushing to a PR branch
# The second run (usually pull_request) cancels the first (push)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-maven-build.yml@288f393bf5407c87ffd95c128cdf694761941308 # v0.2.0
    secrets: inherit
