# Example: Pyprojectx verification workflow
# Copy this file to .github/workflows/python-verify.yml in your repository

name: Python Verify

on:
  push:
    branches: [main, "feature/*", "fix/*", "dependabot/**"]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  verify:
    # Run on push events, OR on pull_request only if from a fork
    # This prevents duplicate runs: push handles internal branches, PR handles forks
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: cuioss/cuioss-organization/.github/workflows/reusable-pyprojectx-verify.yml@288f393bf5407c87ffd95c128cdf694761941308 # v0.2.0
    # Optional inputs (all have sensible defaults):
    # with:
    #   python-version: '3.12'           # Leave empty to let uv manage from pyproject.toml
    #   cache-dependency-glob: 'uv.lock' # Glob pattern for cache dependencies
    #   upload-artifacts-on-failure: true # Upload test artifacts on failure
    #   verify-command: './pw verify'     # Command to run
