# Example: Copy this to your repo as .github/workflows/scorecards.yml
name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '20 7 * * 2'
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analysis:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-scorecards.yml@fbb87b2940f43cd3c6907c194dbbd437b2a78aa4 # v0.5.0
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
      issues: read
      pull-requests: read
      checks: read
