# Example: Copy this to your repo as .github/workflows/scorecards.yml
name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '20 7 * * 2'
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analysis:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-scorecards.yml@3809a757f2f69d0d12443ea9554af0136ba66320 # v0.2.1
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
      issues: read
      pull-requests: read
      checks: read
