name: 'Read project.yml Configuration'
description: 'Parses .github/project.yml and outputs configuration values with defaults'
author: 'cuioss'

branding:
  icon: 'settings'
  color: 'blue'

inputs:
  config-path:
    description: 'Path to project.yml file'
    required: false
    default: '.github/project.yml'

outputs:
  # Maven Build Section
  java-versions:
    description: 'JSON array of Java versions for matrix build'
    value: ${{ steps.config.outputs.java-versions }}
  java-version:
    description: 'Primary Java version for Sonar analysis and snapshot deploy'
    value: ${{ steps.config.outputs.java-version }}
  enable-snapshot-deploy:
    description: 'Deploy snapshots to Maven Central'
    value: ${{ steps.config.outputs.enable-snapshot-deploy }}
  maven-profiles-snapshot:
    description: 'Maven profiles for snapshot deployment'
    value: ${{ steps.config.outputs.maven-profiles-snapshot }}
  maven-profiles-release:
    description: 'Maven profiles for release'
    value: ${{ steps.config.outputs.maven-profiles-release }}
  npm-cache:
    description: 'Enable npm package caching'
    value: ${{ steps.config.outputs.npm-cache }}
  skip-on-docs-only:
    description: 'Skip build when only documentation/config files changed'
    value: ${{ steps.config.outputs.skip-on-docs-only }}
  paths-ignore-extra:
    description: 'Space-separated extra glob patterns to treat as non-code'
    value: ${{ steps.config.outputs.paths-ignore-extra }}

  # npm Build Section
  npm-node-version:
    description: 'Node.js version for npm builds'
    value: ${{ steps.config.outputs.npm-node-version }}
  npm-registry-url:
    description: 'npm registry URL'
    value: ${{ steps.config.outputs.npm-registry-url }}

  # Sonar Section
  sonar-enabled:
    description: 'Enable SonarCloud analysis'
    value: ${{ steps.config.outputs.sonar-enabled }}
  sonar-skip-on-dependabot:
    description: 'Skip Sonar analysis for Dependabot PRs'
    value: ${{ steps.config.outputs.sonar-skip-on-dependabot }}
  sonar-project-key:
    description: 'SonarCloud project key'
    value: ${{ steps.config.outputs.sonar-project-key }}

  # Release Section
  current-version:
    description: 'Current release version'
    value: ${{ steps.config.outputs.current-version }}
  next-version:
    description: 'Next development version'
    value: ${{ steps.config.outputs.next-version }}
  create-github-release:
    description: 'Create a GitHub Release with auto-generated notes'
    value: ${{ steps.config.outputs.create-github-release }}

  # Pages Section
  pages-reference:
    description: 'Folder on cuioss.github.io for Maven site'
    value: ${{ steps.config.outputs.pages-reference }}
  deploy-site:
    description: 'Deploy Maven site to GitHub Pages during release'
    value: ${{ steps.config.outputs.deploy-site }}

  # Integration Tests Section
  it-test-type:
    description: 'Type of integration tests (java-it or playwright-e2e)'
    value: ${{ steps.config.outputs.it-test-type }}
  it-maven-module:
    description: 'Maven module containing integration tests'
    value: ${{ steps.config.outputs.it-maven-module }}
  it-maven-profiles:
    description: 'Maven profiles for integration tests'
    value: ${{ steps.config.outputs.it-maven-profiles }}
  it-timeout-minutes:
    description: 'Timeout in minutes for the test job'
    value: ${{ steps.config.outputs.it-timeout-minutes }}
  it-deploy-reports:
    description: 'Deploy test reports to cuioss.github.io'
    value: ${{ steps.config.outputs.it-deploy-reports }}
  it-reports-subfolder:
    description: 'Subfolder on cuioss.github.io for test reports'
    value: ${{ steps.config.outputs.it-reports-subfolder }}
  it-reports-folder:
    description: 'Project-relative path to the folder containing reports to deploy'
    value: ${{ steps.config.outputs.it-reports-folder }}

  # Pyprojectx Section
  pyprojectx-python-version:
    description: 'Python version (empty = let uv manage from pyproject.toml)'
    value: ${{ steps.config.outputs.pyprojectx-python-version }}
  pyprojectx-cache-dependency-glob:
    description: 'Glob pattern for uv cache dependencies'
    value: ${{ steps.config.outputs.pyprojectx-cache-dependency-glob }}
  pyprojectx-upload-artifacts-on-failure:
    description: 'Upload test artifacts on failure'
    value: ${{ steps.config.outputs.pyprojectx-upload-artifacts-on-failure }}
  pyprojectx-verify-command:
    description: 'Verification command to run'
    value: ${{ steps.config.outputs.pyprojectx-verify-command }}

  # GitHub Automation Section
  auto-merge-build-versions:
    description: 'Auto-merge consumer repo workflow update PRs when CI passes'
    value: ${{ steps.config.outputs.auto-merge-build-versions }}
  # Consumers
  consumers:
    description: 'Space-separated list of consumer repositories'
    value: ${{ steps.config.outputs.consumers }}

  # Custom namespace (for downstream repos)
  # Custom fields are output as custom-<key> (e.g., custom.my-flag -> custom-my-flag)
  custom-keys:
    description: 'Space-separated list of custom field keys defined in project.yml'
    value: ${{ steps.config.outputs.custom-keys }}

  # Meta
  config-found:
    description: 'Whether project.yml was found'
    value: ${{ steps.config.outputs.config-found }}

runs:
  using: 'composite'
  steps:
    - name: Read project.yml configuration
      id: config
      shell: bash
      run: python3 "${{ github.action_path }}/read-config.py" --config "${{ inputs.config-path }}" >> $GITHUB_OUTPUT
